spring:
  datasource:
    url: jdbc:mysql://localhost:3306/univers
    username: root
    password: Harbinger1945
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://demo-mysql:3306/univers?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Harbinger1945
    driver-class-name: com.mysql.cj.jdbc.Driver